#!/usr/bin/env node

const fs = require( 'fs-extra' );
const path = require( 'path' );
const fetch = require( 'node-fetch' );

function getPath( ...fileOrDir ) {
    return path.join( __dirname, ...fileOrDir );
}

function treeUrl( tree ) {
    return  'https://api.github.com/repos/twitter/twemoji/git/trees/' + tree;
}

function getTree( tree ) {
    const url  = treeUrl(tree);

    return fetch(url, {
        method: 'get',
        headers: { 'Accept': 'application/vnd.github.v3+json' },
    })
    .then(res => res.json());
}

getTree( 'master' ).then( res => {
    const assetsFolderSha = res.tree.filter( t => t.path === 'assets')[0].sha;

    getTree( assetsFolderSha ).then( res => {
        const svgFolderSha = res.tree.filter( t => t.path === 'svg')[0].sha;

        const extLength = ".svg".length;

        getTree( svgFolderSha ).then( res => {
            const list = res.tree.map(item=>{
                const path = item.path;

                return path.substring( 0, path.length - extLength )
            });

            save(list);
        });
    });
}).catch(console.error);

function save( list ) {
    const outputFile = getPath( 'src/', 'supported-emojis.json' );

    fs.writeJsonSync( outputFile, { list: list } );

    console.log( "Supported emojis list file saved in %s", outputFile );
}